# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from UI.RSA_UI import RSA_UI
from UI.EG_UI import EG_UI
from UI.P_UI import P_UI


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 609)
        self.rsa_alg = QtWidgets.QTabWidget(Dialog)
        self.rsa_alg.setGeometry(QtCore.QRect(-4, -1, 411, 611))
        self.rsa_alg.setObjectName("rsa_alg")
        # -----------------------------------------------------------------
        self.tab = RSA_UI()
        self.rsa_alg.addTab(self.tab, "")
        # -----------------------------------------------------------------
        self.tab_2 = EG_UI()
        self.rsa_alg.addTab(self.tab_2, "")
        # -----------------------------------------------------------------
        self.tab_3 = P_UI()
        self.rsa_alg.addTab(self.tab_3, "")
        # -----------------------------------------------------------------
        self.retranslateUi(Dialog)
        self.rsa_alg.setCurrentIndex(0)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.tab.retranslateUi(Dialog)
        self.rsa_alg.setTabText(self.rsa_alg.indexOf(self.tab), _translate("Dialog", "RSA"))

        self.tab_2.retranslateUi(Dialog)
        self.rsa_alg.setTabText(self.rsa_alg.indexOf(self.tab_2), _translate("Dialog", "ElGamal"))

        self.tab_3.retranslateUi(Dialog)
        self.rsa_alg.setTabText(self.rsa_alg.indexOf(self.tab_3), _translate("Dialog", "Paillier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
