# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Algorithm import *
from Key import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 609)
        self.rsa_alg = QtWidgets.QTabWidget(Dialog)
        self.rsa_alg.setGeometry(QtCore.QRect(-4, -1, 411, 611))
        self.rsa_alg.setObjectName("rsa_alg")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.rsa_opt = QtWidgets.QTabWidget(self.tab)
        self.rsa_opt.setGeometry(QtCore.QRect(0, 0, 411, 591))
        self.rsa_opt.setObjectName("rsa_opt")
        # -----------------------------------------------------------------
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")

        self.rsa_gen_len_lbl = QtWidgets.QLabel(self.tab_5)
        self.rsa_gen_len_lbl.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.rsa_gen_len_lbl.setObjectName("rsa_gen_len_lbl")

        self.rsa_gen_len_text = QtWidgets.QLineEdit(self.tab_5)
        self.rsa_gen_len_text.setGeometry(QtCore.QRect(110, 30, 261, 20))
        self.rsa_gen_len_text.setObjectName("rsa_gen_len_text")

        self.rsa_gen_lbl = QtWidgets.QLabel(self.tab_5)
        self.rsa_gen_lbl.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.rsa_gen_lbl.setObjectName("rsa_gen_lbl")

        self.rsa_gen_file_text = QtWidgets.QLineEdit(self.tab_5)
        self.rsa_gen_file_text.setGeometry(QtCore.QRect(110, 60, 261, 20))
        self.rsa_gen_file_text.setObjectName("rsa_gen_file_text")

        self.rsa_gen_button = QtWidgets.QPushButton(self.tab_5)
        self.rsa_gen_button.setGeometry(QtCore.QRect(170, 120, 75, 23))
        self.rsa_gen_button.setObjectName("rsa_gen_button")

        self.rsa_gen_file_lbl = QtWidgets.QLabel(self.tab_5)
        self.rsa_gen_file_lbl.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.rsa_gen_file_lbl.setObjectName("rsa_gen_file_lbl")

        self.rsa_gen_dir_button = QtWidgets.QPushButton(self.tab_5)
        self.rsa_gen_dir_button.setGeometry(QtCore.QRect(10, 90, 111, 23))
        self.rsa_gen_dir_button.setObjectName("rsa_gen_dir_button")

        self.rsa_gen_dir_name = QtWidgets.QLabel(self.tab_5)
        self.rsa_gen_dir_name.setGeometry(QtCore.QRect(130, 100, 261, 16))
        self.rsa_gen_dir_name.setObjectName("rsa_gen_dir_name")

        self.rsa_opt.addTab(self.tab_5, "")
        # -----------------------------------------------------------------
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")

        self.rsa_enc_n_lbl = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_n_lbl.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.rsa_enc_n_lbl.setObjectName("rsa_enc_n_lbl")

        self.rsa_enc_n_text = QtWidgets.QTextEdit(self.tab_6)
        self.rsa_enc_n_text.setGeometry(QtCore.QRect(80, 20, 301, 64))
        self.rsa_enc_n_text.setObjectName("rsa_enc_n_text")

        self.rsa_enc_key_file_lbl = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_key_file_lbl.setGeometry(QtCore.QRect(60, 170, 21, 16))
        self.rsa_enc_key_file_lbl.setObjectName("rsa_enc_key_file_lbl")

        self.rsa_enc_key_file_button = QtWidgets.QPushButton(self.tab_6)
        self.rsa_enc_key_file_button.setGeometry(QtCore.QRect(80, 170, 81, 23))
        self.rsa_enc_key_file_button.setObjectName("rsa_enc_key_file_button")

        self.rsa_enc_e_lbl = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_e_lbl.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.rsa_enc_e_lbl.setObjectName("rsa_enc_e_lbl")

        self.rsa_enc_e_text = QtWidgets.QTextEdit(self.tab_6)
        self.rsa_enc_e_text.setGeometry(QtCore.QRect(80, 90, 301, 64))
        self.rsa_enc_e_text.setObjectName("rsa_enc_e_text")

        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(10, 230, 61, 16))
        self.label_16.setObjectName("label_16")

        self.rsa_enc_m_text = QtWidgets.QTextEdit(self.tab_6)
        self.rsa_enc_m_text.setGeometry(QtCore.QRect(80, 230, 301, 64))
        self.rsa_enc_m_text.setObjectName("rsa_enc_m_text")

        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(60, 300, 21, 16))
        self.label_17.setObjectName("label_17")

        self.rsa_enc_m_file_button = QtWidgets.QPushButton(self.tab_6)
        self.rsa_enc_m_file_button.setGeometry(QtCore.QRect(80, 300, 81, 23))
        self.rsa_enc_m_file_button.setObjectName("rsa_enc_m_file_button")

        self.rsa_enc_key_lbl = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_key_lbl.setGeometry(QtCore.QRect(10, 0, 47, 14))
        self.rsa_enc_key_lbl.setObjectName("rsa_enc_key_lbl")

        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(10, 210, 47, 14))
        self.label_19.setObjectName("label_19")

        self.line = QtWidgets.QFrame(self.tab_6)
        self.line.setGeometry(QtCore.QRect(0, 200, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(10, 330, 47, 14))
        self.label_20.setObjectName("label_20")

        self.rsa_enc_save_file_button = QtWidgets.QPushButton(self.tab_6)
        self.rsa_enc_save_file_button.setGeometry(QtCore.QRect(80, 330, 81, 23))
        self.rsa_enc_save_file_button.setObjectName("rsa_enc_save_file_button")

        self.rsa_enc_button = QtWidgets.QPushButton(self.tab_6)
        self.rsa_enc_button.setGeometry(QtCore.QRect(170, 360, 75, 23))
        self.rsa_enc_button.setObjectName("rsa_enc_button")

        self.rsa_enc_res_button = QtWidgets.QTextEdit(self.tab_6)
        self.rsa_enc_res_button.setGeometry(QtCore.QRect(80, 390, 301, 64))
        self.rsa_enc_res_button.setObjectName("rsa_enc_res_button")

        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(10, 390, 61, 16))
        self.label_30.setObjectName("label_30")

        self.rsa_enc_key_file_name = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_key_file_name.setGeometry(QtCore.QRect(170, 180, 211, 16))
        self.rsa_enc_key_file_name.setObjectName("rsa_enc_key_file_name")

        self.rsa_enc_m_file_button_2 = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_m_file_button_2.setGeometry(QtCore.QRect(170, 310, 211, 16))
        self.rsa_enc_m_file_button_2.setObjectName("rsa_enc_m_file_button_2")

        self.rsa_enc_save_file_button_2 = QtWidgets.QLabel(self.tab_6)
        self.rsa_enc_save_file_button_2.setGeometry(QtCore.QRect(170, 340, 211, 16))
        self.rsa_enc_save_file_button_2.setObjectName("rsa_enc_save_file_button_2")

        self.rsa_opt.addTab(self.tab_6, "")
        # -----------------------------------------------------------------
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")

        self.label_21 = QtWidgets.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(10, 240, 61, 16))
        self.label_21.setObjectName("label_21")

        self.rsa_dec_m_text = QtWidgets.QTextEdit(self.tab_7)
        self.rsa_dec_m_text.setGeometry(QtCore.QRect(80, 240, 301, 64))
        self.rsa_dec_m_text.setObjectName("rsa_dec_m_text")

        self.rsa_dec_m_file_button = QtWidgets.QPushButton(self.tab_7)
        self.rsa_dec_m_file_button.setGeometry(QtCore.QRect(80, 310, 81, 23))
        self.rsa_dec_m_file_button.setObjectName("rsa_dec_m_file_button")

        self.rsa_dec_button = QtWidgets.QPushButton(self.tab_7)
        self.rsa_dec_button.setGeometry(QtCore.QRect(170, 370, 75, 23))
        self.rsa_dec_button.setObjectName("rsa_dec_button")

        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 47, 14))
        self.label_22.setObjectName("label_22")

        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setGeometry(QtCore.QRect(60, 180, 21, 16))
        self.label_23.setObjectName("label_23")

        self.label_24 = QtWidgets.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(60, 310, 21, 16))
        self.label_24.setObjectName("label_24")

        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(10, 340, 47, 14))
        self.label_25.setObjectName("label_25")

        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_26.setObjectName("label_26")

        self.rsa_dec_save_file_button = QtWidgets.QPushButton(self.tab_7)
        self.rsa_dec_save_file_button.setGeometry(QtCore.QRect(80, 340, 81, 23))
        self.rsa_dec_save_file_button.setObjectName("rsa_dec_save_file_button")

        self.rsa_dec_key_file_button = QtWidgets.QPushButton(self.tab_7)
        self.rsa_dec_key_file_button.setGeometry(QtCore.QRect(80, 180, 81, 23))
        self.rsa_dec_key_file_button.setObjectName("rsa_dec_key_file_button")

        self.rsa_dec_d_text = QtWidgets.QTextEdit(self.tab_7)
        self.rsa_dec_d_text.setGeometry(QtCore.QRect(80, 100, 301, 64))
        self.rsa_dec_d_text.setObjectName("rsa_dec_d_text")

        self.label_27 = QtWidgets.QLabel(self.tab_7)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_27.setObjectName("label_27")

        self.rsa_dec_n_text = QtWidgets.QTextEdit(self.tab_7)
        self.rsa_dec_n_text.setGeometry(QtCore.QRect(80, 30, 301, 64))
        self.rsa_dec_n_text.setObjectName("rsa_dec_n_text")

        self.label_28 = QtWidgets.QLabel(self.tab_7)
        self.label_28.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label_28.setObjectName("label_28")

        self.line_2 = QtWidgets.QFrame(self.tab_7)
        self.line_2.setGeometry(QtCore.QRect(0, 210, 411, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.rsa_dec_res_button = QtWidgets.QTextEdit(self.tab_7)
        self.rsa_dec_res_button.setGeometry(QtCore.QRect(80, 400, 301, 64))
        self.rsa_dec_res_button.setObjectName("rsa_dec_res_button")

        self.label_29 = QtWidgets.QLabel(self.tab_7)
        self.label_29.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.label_29.setObjectName("label_29")

        self.rsa_dec_m_file_name = QtWidgets.QLabel(self.tab_7)
        self.rsa_dec_m_file_name.setGeometry(QtCore.QRect(170, 320, 211, 16))
        self.rsa_dec_m_file_name.setObjectName("rsa_dec_m_file_name")

        self.rsa_dec_save_file_name = QtWidgets.QLabel(self.tab_7)
        self.rsa_dec_save_file_name.setGeometry(QtCore.QRect(170, 350, 211, 16))
        self.rsa_dec_save_file_name.setObjectName("rsa_dec_save_file_name")

        self.rsa_dec_key_file_name = QtWidgets.QLabel(self.tab_7)
        self.rsa_dec_key_file_name.setGeometry(QtCore.QRect(170, 190, 211, 16))
        self.rsa_dec_key_file_name.setObjectName("rsa_dec_key_file_name")

        self.rsa_opt.addTab(self.tab_7, "")
        self.rsa_alg.addTab(self.tab, "")
        # -----------------------------------------------------------------
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.eg_opt = QtWidgets.QTabWidget(self.tab_2)
        self.eg_opt.setGeometry(QtCore.QRect(0, 0, 411, 591))
        self.eg_opt.setObjectName("eg_opt")

        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")

        self.label_7 = QtWidgets.QLabel(self.tab_8)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_7.setObjectName("label_7")

        self.eg_gen_len_text = QtWidgets.QLineEdit(self.tab_8)
        self.eg_gen_len_text.setGeometry(QtCore.QRect(112, 30, 261, 20))
        self.eg_gen_len_text.setObjectName("eg_gen_len_text")

        self.label_2 = QtWidgets.QLabel(self.tab_8)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_2.setObjectName("label_2")

        self.eg_gen_file_text = QtWidgets.QLineEdit(self.tab_8)
        self.eg_gen_file_text.setGeometry(QtCore.QRect(112, 60, 261, 20))
        self.eg_gen_file_text.setObjectName("eg_gen_file_text")

        self.eg_gen_button = QtWidgets.QPushButton(self.tab_8)
        self.eg_gen_button.setGeometry(QtCore.QRect(170, 120, 75, 23))
        self.eg_gen_button.setObjectName("eg_gen_button")

        self.label_8 = QtWidgets.QLabel(self.tab_8)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_8.setObjectName("label_8")

        self.eg_gen_dir_button = QtWidgets.QPushButton(self.tab_8)
        self.eg_gen_dir_button.setGeometry(QtCore.QRect(10, 90, 111, 23))
        self.eg_gen_dir_button.setObjectName("eg_gen_dir_button")

        self.eg_gen_dir_name = QtWidgets.QLabel(self.tab_8)
        self.eg_gen_dir_name.setGeometry(QtCore.QRect(130, 100, 261, 16))
        self.eg_gen_dir_name.setObjectName("eg_gen_dir_name")

        self.eg_opt.addTab(self.tab_8, "")
        # -----------------------------------------------------------------
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")

        self.label_31 = QtWidgets.QLabel(self.tab_9)
        self.label_31.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_31.setObjectName("label_31")

        self.eg_enc_p_text = QtWidgets.QTextEdit(self.tab_9)
        self.eg_enc_p_text.setGeometry(QtCore.QRect(80, 20, 301, 64))
        self.eg_enc_p_text.setObjectName("eg_enc_p_text")

        self.label_32 = QtWidgets.QLabel(self.tab_9)
        self.label_32.setGeometry(QtCore.QRect(60, 230, 21, 16))
        self.label_32.setObjectName("label_32")

        self.eg_enc_key_file_button = QtWidgets.QPushButton(self.tab_9)
        self.eg_enc_key_file_button.setGeometry(QtCore.QRect(80, 230, 81, 23))
        self.eg_enc_key_file_button.setObjectName("eg_enc_key_file_button")

        self.label_33 = QtWidgets.QLabel(self.tab_9)
        self.label_33.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_33.setObjectName("label_33")

        self.eg_enc_g_text = QtWidgets.QTextEdit(self.tab_9)
        self.eg_enc_g_text.setGeometry(QtCore.QRect(80, 90, 301, 64))
        self.eg_enc_g_text.setObjectName("eg_enc_g_text")

        self.label_34 = QtWidgets.QLabel(self.tab_9)
        self.label_34.setGeometry(QtCore.QRect(10, 290, 61, 16))
        self.label_34.setObjectName("label_34")

        self.eg_enc_m_text = QtWidgets.QTextEdit(self.tab_9)
        self.eg_enc_m_text.setGeometry(QtCore.QRect(80, 290, 301, 64))
        self.eg_enc_m_text.setObjectName("eg_enc_m_text")

        self.label_35 = QtWidgets.QLabel(self.tab_9)
        self.label_35.setGeometry(QtCore.QRect(60, 360, 21, 16))
        self.label_35.setObjectName("label_35")

        self.eg_enc_m_file_button = QtWidgets.QPushButton(self.tab_9)
        self.eg_enc_m_file_button.setGeometry(QtCore.QRect(80, 360, 81, 23))
        self.eg_enc_m_file_button.setObjectName("eg_enc_m_file_button")

        self.label_36 = QtWidgets.QLabel(self.tab_9)
        self.label_36.setGeometry(QtCore.QRect(10, 0, 47, 14))
        self.label_36.setObjectName("label_36")

        self.label_37 = QtWidgets.QLabel(self.tab_9)
        self.label_37.setGeometry(QtCore.QRect(10, 270, 47, 14))
        self.label_37.setObjectName("label_37")

        self.line_3 = QtWidgets.QFrame(self.tab_9)
        self.line_3.setGeometry(QtCore.QRect(0, 260, 411, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.label_38 = QtWidgets.QLabel(self.tab_9)
        self.label_38.setGeometry(QtCore.QRect(10, 390, 47, 14))
        self.label_38.setObjectName("label_38")

        self.eg_enc_save_file_button = QtWidgets.QPushButton(self.tab_9)
        self.eg_enc_save_file_button.setGeometry(QtCore.QRect(80, 390, 81, 23))
        self.eg_enc_save_file_button.setObjectName("eg_enc_save_file_button")

        self.eg_enc_button = QtWidgets.QPushButton(self.tab_9)
        self.eg_enc_button.setGeometry(QtCore.QRect(170, 420, 75, 23))
        self.eg_enc_button.setObjectName("eg_enc_button")

        self.eg_enc_res_text = QtWidgets.QTextEdit(self.tab_9)
        self.eg_enc_res_text.setGeometry(QtCore.QRect(80, 450, 301, 64))
        self.eg_enc_res_text.setObjectName("eg_enc_res_text")

        self.label_39 = QtWidgets.QLabel(self.tab_9)
        self.label_39.setGeometry(QtCore.QRect(10, 450, 61, 16))
        self.label_39.setObjectName("label_39")

        self.eg_enc_y_text = QtWidgets.QTextEdit(self.tab_9)
        self.eg_enc_y_text.setGeometry(QtCore.QRect(80, 160, 301, 64))
        self.eg_enc_y_text.setObjectName("eg_enc_y_text")

        self.label_49 = QtWidgets.QLabel(self.tab_9)
        self.label_49.setGeometry(QtCore.QRect(10, 160, 61, 16))
        self.label_49.setObjectName("label_49")

        self.eg_enc_key_file_name = QtWidgets.QLabel(self.tab_9)
        self.eg_enc_key_file_name.setGeometry(QtCore.QRect(170, 240, 211, 16))
        self.eg_enc_key_file_name.setObjectName("eg_enc_key_file_name")

        self.eg_enc_m_file_name = QtWidgets.QLabel(self.tab_9)
        self.eg_enc_m_file_name.setGeometry(QtCore.QRect(170, 370, 211, 16))
        self.eg_enc_m_file_name.setObjectName("eg_enc_m_file_name")

        self.eg_enc_save_file_name = QtWidgets.QLabel(self.tab_9)
        self.eg_enc_save_file_name.setGeometry(QtCore.QRect(170, 400, 211, 16))
        self.eg_enc_save_file_name.setObjectName("eg_enc_save_file_name")
        self.eg_opt.addTab(self.tab_9, "")
        # -----------------------------------------------------------------
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")

        self.label_40 = QtWidgets.QLabel(self.tab_10)
        self.label_40.setGeometry(QtCore.QRect(10, 240, 61, 16))
        self.label_40.setObjectName("label_40")

        self.eg_dec_m_text = QtWidgets.QTextEdit(self.tab_10)
        self.eg_dec_m_text.setGeometry(QtCore.QRect(80, 240, 301, 64))
        self.eg_dec_m_text.setObjectName("eg_dec_m_text")

        self.eg_dec_m_file_text = QtWidgets.QPushButton(self.tab_10)
        self.eg_dec_m_file_text.setGeometry(QtCore.QRect(80, 310, 81, 23))
        self.eg_dec_m_file_text.setObjectName("eg_dec_m_file_text")

        self.eg_dec_button = QtWidgets.QPushButton(self.tab_10)
        self.eg_dec_button.setGeometry(QtCore.QRect(170, 370, 75, 23))
        self.eg_dec_button.setObjectName("eg_dec_button")

        self.label_41 = QtWidgets.QLabel(self.tab_10)
        self.label_41.setGeometry(QtCore.QRect(10, 10, 47, 14))
        self.label_41.setObjectName("label_41")

        self.label_42 = QtWidgets.QLabel(self.tab_10)
        self.label_42.setGeometry(QtCore.QRect(60, 180, 21, 16))
        self.label_42.setObjectName("label_42")

        self.label_43 = QtWidgets.QLabel(self.tab_10)
        self.label_43.setGeometry(QtCore.QRect(60, 310, 21, 16))
        self.label_43.setObjectName("label_43")

        self.label_44 = QtWidgets.QLabel(self.tab_10)
        self.label_44.setGeometry(QtCore.QRect(10, 340, 47, 14))
        self.label_44.setObjectName("label_44")

        self.label_45 = QtWidgets.QLabel(self.tab_10)
        self.label_45.setGeometry(QtCore.QRect(10, 100, 61, 21))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())

        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")

        self.eg_dec_save_file_text = QtWidgets.QPushButton(self.tab_10)
        self.eg_dec_save_file_text.setGeometry(QtCore.QRect(80, 340, 81, 23))
        self.eg_dec_save_file_text.setObjectName("eg_dec_save_file_text")

        self.eg_dec_key_file_button = QtWidgets.QPushButton(self.tab_10)
        self.eg_dec_key_file_button.setGeometry(QtCore.QRect(80, 180, 81, 23))
        self.eg_dec_key_file_button.setObjectName("eg_dec_key_file_button")

        self.eg_dec_x_text = QtWidgets.QTextEdit(self.tab_10)
        self.eg_dec_x_text.setGeometry(QtCore.QRect(80, 100, 301, 64))
        self.eg_dec_x_text.setObjectName("eg_dec_x_text")

        self.label_46 = QtWidgets.QLabel(self.tab_10)
        self.label_46.setGeometry(QtCore.QRect(10, 30, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName("label_46")

        self.eg_dec_p_text = QtWidgets.QTextEdit(self.tab_10)
        self.eg_dec_p_text.setGeometry(QtCore.QRect(80, 30, 301, 64))
        self.eg_dec_p_text.setObjectName("eg_dec_p_text")

        self.label_47 = QtWidgets.QLabel(self.tab_10)
        self.label_47.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label_47.setObjectName("label_47")

        self.line_4 = QtWidgets.QFrame(self.tab_10)
        self.line_4.setGeometry(QtCore.QRect(0, 210, 411, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.eg_dec_res_text = QtWidgets.QTextEdit(self.tab_10)
        self.eg_dec_res_text.setGeometry(QtCore.QRect(80, 400, 301, 64))
        self.eg_dec_res_text.setObjectName("eg_dec_res_text")

        self.label_48 = QtWidgets.QLabel(self.tab_10)
        self.label_48.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.label_48.setObjectName("label_48")

        self.eg_dec_key_file_name = QtWidgets.QLabel(self.tab_10)
        self.eg_dec_key_file_name.setGeometry(QtCore.QRect(180, 190, 201, 20))
        self.eg_dec_key_file_name.setObjectName("eg_dec_key_file_name")

        self.eg_dec_m_file_name = QtWidgets.QLabel(self.tab_10)
        self.eg_dec_m_file_name.setGeometry(QtCore.QRect(170, 320, 211, 16))
        self.eg_dec_m_file_name.setObjectName("eg_dec_m_file_name")

        self.eg_dec_save_file_name = QtWidgets.QLabel(self.tab_10)
        self.eg_dec_save_file_name.setGeometry(QtCore.QRect(170, 350, 211, 16))
        self.eg_dec_save_file_name.setObjectName("eg_dec_save_file_name")

        self.eg_opt.addTab(self.tab_10, "")
        self.rsa_alg.addTab(self.tab_2, "")
        # -----------------------------------------------------------------
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.p_opt = QtWidgets.QTabWidget(self.tab_3)
        self.p_opt.setGeometry(QtCore.QRect(0, 0, 411, 591))
        self.p_opt.setObjectName("p_opt")

        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")

        self.label_9 = QtWidgets.QLabel(self.tab_11)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_9.setObjectName("label_9")

        self.p_gen_len_text = QtWidgets.QLineEdit(self.tab_11)
        self.p_gen_len_text.setGeometry(QtCore.QRect(110, 30, 261, 20))
        self.p_gen_len_text.setObjectName("p_gen_len_text")

        self.label_3 = QtWidgets.QLabel(self.tab_11)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_3.setObjectName("label_3")

        self.p_gen_file_text = QtWidgets.QLineEdit(self.tab_11)
        self.p_gen_file_text.setGeometry(QtCore.QRect(110, 60, 261, 20))
        self.p_gen_file_text.setObjectName("p_gen_file_text")

        self.p_gen_button = QtWidgets.QPushButton(self.tab_11)
        self.p_gen_button.setGeometry(QtCore.QRect(170, 120, 75, 23))
        self.p_gen_button.setObjectName("p_gen_button")

        self.label_10 = QtWidgets.QLabel(self.tab_11)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_10.setObjectName("label_10")

        self.p_gen_dir_button = QtWidgets.QPushButton(self.tab_11)
        self.p_gen_dir_button.setGeometry(QtCore.QRect(10, 90, 121, 23))
        self.p_gen_dir_button.setObjectName("p_gen_dir_button")

        self.p_gen_dir_name = QtWidgets.QLabel(self.tab_11)
        self.p_gen_dir_name.setGeometry(QtCore.QRect(140, 100, 251, 20))
        self.p_gen_dir_name.setObjectName("p_gen_dir_name")
        self.p_opt.addTab(self.tab_11, "")
        # -----------------------------------------------------------------
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")

        self.label_50 = QtWidgets.QLabel(self.tab_12)
        self.label_50.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_50.setObjectName("label_50")

        self.p_enc_g_text = QtWidgets.QTextEdit(self.tab_12)
        self.p_enc_g_text.setGeometry(QtCore.QRect(80, 20, 301, 64))
        self.p_enc_g_text.setObjectName("p_enc_g_text")

        self.label_51 = QtWidgets.QLabel(self.tab_12)
        self.label_51.setGeometry(QtCore.QRect(60, 170, 21, 16))
        self.label_51.setObjectName("label_51")

        self.p_enc_key_file_button = QtWidgets.QPushButton(self.tab_12)
        self.p_enc_key_file_button.setGeometry(QtCore.QRect(80, 170, 81, 23))
        self.p_enc_key_file_button.setObjectName("p_enc_key_file_button")

        self.label_52 = QtWidgets.QLabel(self.tab_12)
        self.label_52.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_52.setObjectName("label_52")

        self.p_enc_n_text = QtWidgets.QTextEdit(self.tab_12)
        self.p_enc_n_text.setGeometry(QtCore.QRect(80, 90, 301, 64))
        self.p_enc_n_text.setObjectName("p_enc_n_text")

        self.label_53 = QtWidgets.QLabel(self.tab_12)
        self.label_53.setGeometry(QtCore.QRect(10, 230, 61, 16))
        self.label_53.setObjectName("label_53")

        self.p_enc_m_text = QtWidgets.QTextEdit(self.tab_12)
        self.p_enc_m_text.setGeometry(QtCore.QRect(80, 230, 301, 64))
        self.p_enc_m_text.setObjectName("p_enc_m_text")

        self.label_54 = QtWidgets.QLabel(self.tab_12)
        self.label_54.setGeometry(QtCore.QRect(60, 300, 21, 16))
        self.label_54.setObjectName("label_54")

        self.p_enc_m_file_button = QtWidgets.QPushButton(self.tab_12)
        self.p_enc_m_file_button.setGeometry(QtCore.QRect(80, 300, 81, 23))
        self.p_enc_m_file_button.setObjectName("p_enc_m_file_button")

        self.label_55 = QtWidgets.QLabel(self.tab_12)
        self.label_55.setGeometry(QtCore.QRect(10, 0, 47, 14))
        self.label_55.setObjectName("label_55")

        self.label_56 = QtWidgets.QLabel(self.tab_12)
        self.label_56.setGeometry(QtCore.QRect(10, 210, 47, 14))
        self.label_56.setObjectName("label_56")

        self.line_5 = QtWidgets.QFrame(self.tab_12)
        self.line_5.setGeometry(QtCore.QRect(0, 200, 411, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.label_57 = QtWidgets.QLabel(self.tab_12)
        self.label_57.setGeometry(QtCore.QRect(10, 330, 47, 14))
        self.label_57.setObjectName("label_57")

        self.p_enc_save_file_button = QtWidgets.QPushButton(self.tab_12)
        self.p_enc_save_file_button.setGeometry(QtCore.QRect(80, 330, 81, 23))
        self.p_enc_save_file_button.setObjectName("p_enc_save_file_button")

        self.p_enc_button = QtWidgets.QPushButton(self.tab_12)
        self.p_enc_button.setGeometry(QtCore.QRect(170, 360, 75, 23))
        self.p_enc_button.setObjectName("p_enc_button")

        self.p_enc_res_text = QtWidgets.QTextEdit(self.tab_12)
        self.p_enc_res_text.setGeometry(QtCore.QRect(80, 390, 301, 64))
        self.p_enc_res_text.setObjectName("p_enc_res_text")

        self.label_58 = QtWidgets.QLabel(self.tab_12)
        self.label_58.setGeometry(QtCore.QRect(10, 390, 61, 16))
        self.label_58.setObjectName("label_58")

        self.p_enc_key_file_name = QtWidgets.QLabel(self.tab_12)
        self.p_enc_key_file_name.setGeometry(QtCore.QRect(170, 180, 211, 16))
        self.p_enc_key_file_name.setObjectName("p_enc_key_file_name")

        self.p_enc_m_file_name = QtWidgets.QLabel(self.tab_12)
        self.p_enc_m_file_name.setGeometry(QtCore.QRect(170, 310, 211, 16))
        self.p_enc_m_file_name.setObjectName("p_enc_m_file_name")

        self.p_enc_save_file_name = QtWidgets.QLabel(self.tab_12)
        self.p_enc_save_file_name.setGeometry(QtCore.QRect(170, 340, 211, 16))
        self.p_enc_save_file_name.setObjectName("p_enc_save_file_name")
        self.p_opt.addTab(self.tab_12, "")
        # -----------------------------------------------------------------
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")

        self.label_59 = QtWidgets.QLabel(self.tab_13)
        self.label_59.setGeometry(QtCore.QRect(10, 240, 61, 16))
        self.label_59.setObjectName("label_59")

        self.p_dec_m_text = QtWidgets.QTextEdit(self.tab_13)
        self.p_dec_m_text.setGeometry(QtCore.QRect(80, 240, 301, 64))
        self.p_dec_m_text.setObjectName("p_dec_m_text")

        self.p_dec_m_file_button = QtWidgets.QPushButton(self.tab_13)
        self.p_dec_m_file_button.setGeometry(QtCore.QRect(80, 310, 81, 23))
        self.p_dec_m_file_button.setObjectName("p_dec_m_file_button")

        self.p_dec_button = QtWidgets.QPushButton(self.tab_13)
        self.p_dec_button.setGeometry(QtCore.QRect(170, 370, 75, 23))
        self.p_dec_button.setObjectName("p_dec_button")

        self.label_60 = QtWidgets.QLabel(self.tab_13)
        self.label_60.setGeometry(QtCore.QRect(10, 10, 47, 14))
        self.label_60.setObjectName("label_60")

        self.label_61 = QtWidgets.QLabel(self.tab_13)
        self.label_61.setGeometry(QtCore.QRect(60, 180, 21, 16))
        self.label_61.setObjectName("label_61")

        self.label_62 = QtWidgets.QLabel(self.tab_13)
        self.label_62.setGeometry(QtCore.QRect(60, 310, 21, 16))
        self.label_62.setObjectName("label_62")

        self.label_63 = QtWidgets.QLabel(self.tab_13)
        self.label_63.setGeometry(QtCore.QRect(10, 340, 47, 14))
        self.label_63.setObjectName("label_63")

        self.label_64 = QtWidgets.QLabel(self.tab_13)
        self.label_64.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_64.setObjectName("label_64")

        self.p_dec_save_file_button = QtWidgets.QPushButton(self.tab_13)
        self.p_dec_save_file_button.setGeometry(QtCore.QRect(80, 340, 81, 23))
        self.p_dec_save_file_button.setObjectName("p_dec_save_file_button")

        self.p_dec_key_file_button = QtWidgets.QPushButton(self.tab_13)
        self.p_dec_key_file_button.setGeometry(QtCore.QRect(80, 180, 81, 23))
        self.p_dec_key_file_button.setObjectName("p_dec_key_file_button")

        self.p_dec_mu_text = QtWidgets.QTextEdit(self.tab_13)
        self.p_dec_mu_text.setGeometry(QtCore.QRect(80, 100, 301, 64))
        self.p_dec_mu_text.setObjectName("p_dec_mu_text")

        self.label_65 = QtWidgets.QLabel(self.tab_13)
        self.label_65.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_65.setObjectName("label_65")

        self.p_dec_lam_text = QtWidgets.QTextEdit(self.tab_13)
        self.p_dec_lam_text.setGeometry(QtCore.QRect(80, 30, 301, 64))
        self.p_dec_lam_text.setObjectName("p_dec_lam_text")

        self.label_66 = QtWidgets.QLabel(self.tab_13)
        self.label_66.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label_66.setObjectName("label_66")

        self.line_6 = QtWidgets.QFrame(self.tab_13)
        self.line_6.setGeometry(QtCore.QRect(0, 210, 411, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.p_dec_res_text = QtWidgets.QTextEdit(self.tab_13)
        self.p_dec_res_text.setGeometry(QtCore.QRect(80, 400, 301, 64))
        self.p_dec_res_text.setObjectName("p_dec_res_text")

        self.label_67 = QtWidgets.QLabel(self.tab_13)
        self.label_67.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.label_67.setObjectName("label_67")

        self.p_dec_key_file_name = QtWidgets.QLabel(self.tab_13)
        self.p_dec_key_file_name.setGeometry(QtCore.QRect(170, 190, 211, 16))
        self.p_dec_key_file_name.setObjectName("p_dec_key_file_name")

        self.p_dec_save_file_name = QtWidgets.QLabel(self.tab_13)
        self.p_dec_save_file_name.setGeometry(QtCore.QRect(170, 350, 211, 16))
        self.p_dec_save_file_name.setObjectName("p_dec_save_file_name")

        self.p_dec_m_file_name = QtWidgets.QLabel(self.tab_13)
        self.p_dec_m_file_name.setGeometry(QtCore.QRect(170, 320, 211, 16))
        self.p_dec_m_file_name.setObjectName("p_dec_m_file_name")

        self.p_opt.addTab(self.tab_13, "")
        self.rsa_alg.addTab(self.tab_3, "")
        # -----------------------------------------------------------------
        self.retranslateUi(Dialog)
        self.rsa_alg.setCurrentIndex(0)
        self.rsa_opt.setCurrentIndex(0)
        self.eg_opt.setCurrentIndex(0)
        self.p_opt.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.rsa_gen_len_lbl.setText(_translate("Dialog", "Key length (bit):"))
        self.rsa_gen_lbl.setText(_translate("Dialog", "Generate Keys"))
        self.rsa_gen_button.setText(_translate("Dialog", "Generate"))
        self.rsa_gen_file_lbl.setText(_translate("Dialog", "File name:"))
        self.rsa_gen_dir_button.setText(_translate("Dialog", "Choose directory"))
        self.rsa_gen_dir_name.setText(_translate("Dialog", ""))
        self.rsa_opt.setTabText(self.rsa_opt.indexOf(self.tab_5), _translate("Dialog", "Generate"))
        self.rsa_enc_n_lbl.setText(_translate("Dialog", "n"))
        self.rsa_enc_key_file_lbl.setText(_translate("Dialog", "or"))
        self.rsa_enc_key_file_button.setText(_translate("Dialog", "Choose file"))
        self.rsa_enc_e_lbl.setText(_translate("Dialog", "e"))
        self.label_16.setText(_translate("Dialog", "Message"))
        self.label_17.setText(_translate("Dialog", "or"))
        self.rsa_enc_m_file_button.setText(_translate("Dialog", "Choose file"))
        self.rsa_enc_key_lbl.setText(_translate("Dialog", "Key"))
        self.label_19.setText(_translate("Dialog", "Plaintext"))
        self.label_20.setText(_translate("Dialog", "Save"))
        self.rsa_enc_save_file_button.setText(_translate("Dialog", "Choose file"))
        self.rsa_enc_button.setText(_translate("Dialog", "Encrypt"))
        self.label_30.setText(_translate("Dialog", "Result"))
        self.rsa_enc_key_file_name.setText(_translate("Dialog", ""))
        self.rsa_enc_m_file_button_2.setText(_translate("Dialog", ""))
        self.rsa_enc_save_file_button_2.setText(_translate("Dialog", ""))
        self.rsa_opt.setTabText(self.rsa_opt.indexOf(self.tab_6), _translate("Dialog", "Encrypt"))
        self.label_21.setText(_translate("Dialog", "Message"))
        self.rsa_dec_m_file_button.setText(_translate("Dialog", "Choose file"))
        self.rsa_dec_button.setText(_translate("Dialog", "Decrypt"))
        self.label_22.setText(_translate("Dialog", "Key"))
        self.label_23.setText(_translate("Dialog", "or"))
        self.label_24.setText(_translate("Dialog", "or"))
        self.label_25.setText(_translate("Dialog", "Save"))
        self.label_26.setText(_translate("Dialog", "d"))
        self.rsa_dec_save_file_button.setText(_translate("Dialog", "Choose file"))
        self.rsa_dec_key_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_27.setText(_translate("Dialog", "n"))
        self.label_28.setText(_translate("Dialog", "Ciphertext"))
        self.label_29.setText(_translate("Dialog", "Result"))
        self.rsa_dec_m_file_name.setText(_translate("Dialog", ""))
        self.rsa_dec_save_file_name.setText(_translate("Dialog", ""))
        self.rsa_dec_key_file_name.setText(_translate("Dialog", ""))
        self.rsa_opt.setTabText(self.rsa_opt.indexOf(self.tab_7), _translate("Dialog", "Decrypt"))
        self.rsa_alg.setTabText(self.rsa_alg.indexOf(self.tab), _translate("Dialog", "RSA"))
        self.label_7.setText(_translate("Dialog", "Key length (bit):"))
        self.label_2.setText(_translate("Dialog", "Generate Keys"))
        self.eg_gen_button.setText(_translate("Dialog", "Generate"))
        self.label_8.setText(_translate("Dialog", "File name:"))
        self.eg_gen_dir_button.setText(_translate("Dialog", "Choose directory"))
        self.eg_gen_dir_name.setText(_translate("Dialog", ""))
        self.eg_opt.setTabText(self.eg_opt.indexOf(self.tab_8), _translate("Dialog", "Generate"))
        self.label_31.setText(_translate("Dialog", "p"))
        self.label_32.setText(_translate("Dialog", "or"))
        self.eg_enc_key_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_33.setText(_translate("Dialog", "g"))
        self.label_34.setText(_translate("Dialog", "Message"))
        self.label_35.setText(_translate("Dialog", "or"))
        self.eg_enc_m_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_36.setText(_translate("Dialog", "Key"))
        self.label_37.setText(_translate("Dialog", "Plaintext"))
        self.label_38.setText(_translate("Dialog", "Save"))
        self.eg_enc_save_file_button.setText(_translate("Dialog", "Choose file"))
        self.eg_enc_button.setText(_translate("Dialog", "Encrypt"))
        self.label_39.setText(_translate("Dialog", "Result"))
        self.label_49.setText(_translate("Dialog", "y"))
        self.eg_enc_key_file_name.setText(_translate("Dialog", ""))
        self.eg_enc_m_file_name.setText(_translate("Dialog", ""))
        self.eg_enc_save_file_name.setText(_translate("Dialog", ""))
        self.eg_opt.setTabText(self.eg_opt.indexOf(self.tab_9), _translate("Dialog", "Encrypt"))
        self.label_40.setText(_translate("Dialog", "Message"))
        self.eg_dec_m_file_text.setText(_translate("Dialog", "Choose file"))
        self.eg_dec_button.setText(_translate("Dialog", "Decrypt"))
        self.label_41.setText(_translate("Dialog", "Key"))
        self.label_42.setText(_translate("Dialog", "or"))
        self.label_43.setText(_translate("Dialog", "or"))
        self.label_44.setText(_translate("Dialog", "Save"))
        self.label_45.setText(_translate("Dialog", "x"))
        self.eg_dec_save_file_text.setText(_translate("Dialog", "Choose file"))
        self.eg_dec_key_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_46.setText(_translate("Dialog", "p"))
        self.label_47.setText(_translate("Dialog", "Ciphertext"))
        self.label_48.setText(_translate("Dialog", "Result"))
        self.eg_dec_key_file_name.setText(_translate("Dialog", ""))
        self.eg_dec_m_file_name.setText(_translate("Dialog", ""))
        self.eg_dec_save_file_name.setText(_translate("Dialog", ""))
        self.eg_opt.setTabText(self.eg_opt.indexOf(self.tab_10), _translate("Dialog", "Decrypt"))
        self.rsa_alg.setTabText(self.rsa_alg.indexOf(self.tab_2), _translate("Dialog", "ElGamal"))
        self.label_9.setText(_translate("Dialog", "Key length (bit):"))
        self.label_3.setText(_translate("Dialog", "Generate Keys"))
        self.p_gen_button.setText(_translate("Dialog", "Generate"))
        self.label_10.setText(_translate("Dialog", "File name:"))
        self.p_gen_dir_button.setText(_translate("Dialog", "Choose directory"))
        self.p_gen_dir_name.setText(_translate("Dialog", ""))
        self.p_opt.setTabText(self.p_opt.indexOf(self.tab_11), _translate("Dialog", "Generate"))
        self.label_50.setText(_translate("Dialog", "g"))
        self.label_51.setText(_translate("Dialog", "or"))
        self.p_enc_key_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_52.setText(_translate("Dialog", "n"))
        self.label_53.setText(_translate("Dialog", "Message"))
        self.label_54.setText(_translate("Dialog", "or"))
        self.p_enc_m_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_55.setText(_translate("Dialog", "Key"))
        self.label_56.setText(_translate("Dialog", "Plaintext"))
        self.label_57.setText(_translate("Dialog", "Save"))
        self.p_enc_save_file_button.setText(_translate("Dialog", "Choose file"))
        self.p_enc_button.setText(_translate("Dialog", "Encrypt"))
        self.label_58.setText(_translate("Dialog", "Result"))
        self.p_enc_key_file_name.setText(_translate("Dialog", ""))
        self.p_enc_m_file_name.setText(_translate("Dialog", ""))
        self.p_enc_save_file_name.setText(_translate("Dialog", ""))
        self.p_opt.setTabText(self.p_opt.indexOf(self.tab_12), _translate("Dialog", "Encrypt"))
        self.label_59.setText(_translate("Dialog", "Message"))
        self.p_dec_m_file_button.setText(_translate("Dialog", "Choose file"))
        self.p_dec_button.setText(_translate("Dialog", "Decrypt"))
        self.label_60.setText(_translate("Dialog", "Key"))
        self.label_61.setText(_translate("Dialog", "or"))
        self.label_62.setText(_translate("Dialog", "or"))
        self.label_63.setText(_translate("Dialog", "Save"))
        self.label_64.setText(_translate("Dialog", "mu"))
        self.p_dec_save_file_button.setText(_translate("Dialog", "Choose file"))
        self.p_dec_key_file_button.setText(_translate("Dialog", "Choose file"))
        self.label_65.setText(_translate("Dialog", "lambda"))
        self.label_66.setText(_translate("Dialog", "Ciphertext"))
        self.label_67.setText(_translate("Dialog", "Result"))
        self.p_dec_key_file_name.setText(_translate("Dialog", ""))
        self.p_dec_save_file_name.setText(_translate("Dialog", ""))
        self.p_dec_m_file_name.setText(_translate("Dialog", ""))
        self.p_opt.setTabText(self.p_opt.indexOf(self.tab_13), _translate("Dialog", "Decrypt"))
        self.rsa_alg.setTabText(self.rsa_alg.indexOf(self.tab_3), _translate("Dialog", "Paillier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
